### ISSUE TITLE
get.keptn.sh not working for m1 mac

### ISSUE THREAD

**Issue by JJena** [keptn/get.keptn.sh#94]
jjena@MacBook-Air ~ % curl -sL https://get.keptn.sh | bash
The newest version of Keptn is 1.2.0 and will be used automatically
Determined target architecture arm64
Downloading keptn 1.2.0 for OS darwin with architecture arm64 from GitHub: https://github.com/keptn/keptn/releases/download/1.2.0/keptn-1.2.0-darwin-arm64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
An error occured while trying to download keptn from GitHub. Please manually download a release from https://github.com/keptn/keptn/releases.

**Comment by RealAnna** [comment]
Keptn V1 has reached EOL on December 22nd, 2023, so this issue has been closed.
